version: '3'

services:
  web:
    build: .
    container_name: ${CONTAINER_NAME}
    image: "${IMAGE_NAME}:${IMAGE_VERSION:-latest}"
    working_dir: /app
    command: bash -c "npm install && npm run build && node server.js"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "${PORT:-3000}:3000"
