version: '3'

services:
  web:
    command: bash -c "npm install && npm start"
    volumes:
      - ./app/:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${PORT:-3000}:3000"
