version: '3'

services:
  app:
    build: .
    image: "${NAME}:${TAG}"
    container_name: ${NAME}
    working_dir: /app
    command: bash -c "npm install && npm start"
    volumes:
      - ./app/:/app
      - /app/node_modules
    ports:
      - "${PORT}:3000"
